### ISSUE TITLE
Incorrect field order when sending to the client

### ISSUE THREAD

**Issue by DmitryHudrich** [lucasteles/FSharp.MinimalApi#29]
<div height=100>

![image](https://github.com/lucasteles/FSharp.MinimalApi/assets/130711005/5aba028e-b42f-4251-a405-b13c592591e4) 
![image](https://github.com/lucasteles/FSharp.MinimalApi/assets/130711005/a480633d-ba04-4243-915c-768dfdf46e0c)

<p/>

![image](https://github.com/lucasteles/FSharp.MinimalApi/assets/130711005/f5f987bc-6de6-4f99-b881-6042f955c3a5)
![image](https://github.com/lucasteles/FSharp.MinimalApi/assets/130711005/3bec7d71-ed55-4d8c-8ddd-f59998e07815)

When using anonymous types as dto, the order of their fields is sorted alphabetically for some reason. But this does not happen when using existing types. Is this how it should be?

**Comment by lucasteles** [comment]
@DmitryHudrich 

> Is this how it should be?

I have to say **yes**, mostly because this library doesn't have anything with this behavior.

This happens because of how the `F#` compiler emits the anonymous type objects. It creates the class properties in alphabetic order unlike `C#`.

You can see the F# reversed to C# code [here](https://sharplab.io/#v2:DYLgZgzgNAJiDUAfYBTALgAgA4YLwYG9EMA7AQwFsU8MAiAMQHtHaBuDMgc2vwEYAmdgEsYNAQGYMiAL4BYAFBA=) and compare in how the thing happens on C# [here](https://sharplab.io/#v2:CYLg1APgbghgTgAgA4ILwIHYFMDuCDemMAtlmggEQBiA9jRQDQIwDmZ6AjAExMCWw5bgGYEAXwDcQA==)

You can easily see this in the type signature also
<img width="505" alt="image" src="https://github.com/lucasteles/FSharp.MinimalApi/assets/3037609/f46e5ab0-1c1f-4b75-8977-b371f2f0fdfc">
